<?php
/**
 * Created by PhpStorm.
 */

namespace backend\controllers;

use Yii;
use yii\web\Controller;

class AppController extends Controller
{
    /**
     * @param $action
     * @return bool|\yii\web\Response
     * @throws \yii\web\BadRequestHttpException
     */
    public function beforeAction($action)
    {
        if (Yii::$app->getUser()->getIsGuest() && $this->action->id != 'login') {
            return $this->redirect(['site/login']);
        }

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}
