<?php

namespace common\models;

use common\helpers\CollectorHelper;

/**
 * This is the model class for table "order".
 *
 * @property int $id
 * @property int $created_at Дата создания
 * @property int $uin Номер заказа
 * @property string $name Имя
 * @property string $last_name Фамилия
 * @property string $email Email
 * @property string|null $note Примечание к заказу
 * @property string $patronymic Отчество
 */
class Order extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'order';
    }

    /**
     * @return bool
     * @throws \Random\RandomException
     */
    public function beforeValidate()
    {
        $this->created_at = time();
        $this->uin = random_int(100000, 999999);

        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['created_at', 'uin', 'name', 'last_name', 'email', 'patronymic'], 'required'],
            [['created_at', 'uin'], 'integer'],
            [['note'], 'string'],
            [['name', 'last_name', 'email'], 'string', 'max' => 255],
            [['email'], 'email'],
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOrderItems(): \yii\db\ActiveQuery
    {
        return $this->hasMany(OrderItem::class, ['order_id' => 'id']);
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'created_at' => 'Дата заказа',
            'uin' => 'Номер заказа',
            'name' => 'Имя',
            'last_name' => 'Фамилия',
            'email' => 'Email',
            'note' => 'Примечание к заказу',
            'patronymic' => 'Отчество',
        ];
    }

    /**
     * @param $format
     * @return false|string
     */
    public function getCreateDate($format = 'd-m-Y H:i')
    {
        return date($format, $this->created_at);
    }

    /**
     * @param $delimmer
     * @return string
     */
    public function getFullName($delimmer = ' '): string
    {
        return $this->name . $delimmer . $this->last_name . $delimmer . $this->patronymic;
    }

    /**
     * @return string|null
     */
    public function getNote(): ?string
    {
        return $this->note;
    }

    public function getEmail()
    {
        return $this->email;
    }
}
